title: Hello ! Welcome to my personnal blog
description: > # this means to ignore newlines until "baseurl:"
  I'm currently a Developer Advocate at ADEO. I love to share my knowledge about Front-End Development, Cloud and Design through articles, talks and workshops.
  On this blog, you'll find articles about Web Development, JavaScript, CSS, Cloud Computing, Developer Experience, Design and more!
  Feel free to reach out to me on Twitter or LinkedIn if you want to discuss anything.
  Enjoy your stay !
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Thomas Rumas # add your name
author-img: logo.jpg # add your photo
about-author: A curious guy about software engineering, cloud computing, developer experience and also cycling and photography # add description
social-twitter: thomasrumas # add your Twitter handle
social-github: ThomasRumas # add your Github handle
social-linkedin: thomas-rumas-6581a16b # add your Linkedin handle
#social-email: # add your Email address

# Disqus
discus-identifier: thomasrumas # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
